

name: haskell-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        docker-container:
          #- centos:7.6.1810
          - fedora:26
          - fedora:32
    container:
      image: ${{ matrix.docker-container }}
    name: ${{ matrix.docker-container }} in docker
    steps:
      - name: try installing stack
        run: |
          set -ex

          dnf install -y curl

          mkdir -p "root/.local/bin"
          export PATH=root/.local/bin:$PATH

          : "uname"
          uname -a
          : "ls -al"
          ls -al /
          : "id"
          id
          : "set"
          set

          : "try stack install"

          curl -sSL https://get.haskellstack.org/ | sh

          alias stack="stack --stack-root=/root/.stack"
          stack setup
          stack new foo hspec
          cd foo; stack test

          set +ex
