

name: haskell-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        docker-container:
          #- centos:7.6.1810
          - fedora:26
          - fedora:32
    container:
      image: ${{ matrix.docker-container }}
    name: ${{ matrix.docker-container }} in docker
    steps:
      - name: try installing stack
        run: |
          set -ex

          dnf install -y curl

          mkdir -p "$HOME/.local/bin"
          export PATH=$HOME/.local/bin:$PATH

          curl -sSL https://get.haskellstack.org/ | sh
          stack setup
          stack new foo hspec
          cd foo; stack test
          set +ex
