

name: haskell-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        docker-container:
          #- centos:7.6.1810
          - fedora:26
          - fedora:32
        stack-lts:
          - lts-16
          - lts-17
    #container:
    #  image: ${{ matrix.docker-container }}
    name: stack ${{ matrix.stack-lts }} in ${{ matrix.docker-container }}
    steps:
      - uses: actions/checkout@v2
      - name: try installing stack
        run: |
          set -ex

          docker pull ${{ matrix.docker-container }}
          docker run -v $PWD:/opt/work  --workdir /opt/work \
              ${{ matrix.docker-container }} /opt/work/try-stack.sh ${{ matrix.stack-lts }}

          set +ex
